
common: &common
  integrated: true
  verified_addresses:
    - 127.0.0.1
  methods:
    import_user: "method name"

development:
  <<: *common
  wsdl: "wsdl url here"

test:
  <<: *common
  wsdl: "wsdl url here"

production:
  <<: *common
  wsdl: "wsdl url here"
