## facebook settings

appid: "259587414168382"
data-href: "http://apolo11teste.virtual.ufc.br/solar"
tags:
  - <meta property="og:title" content="SOLAR 2.0" />
  - <meta property="og:type" content="university" />
  - <meta property="og:url" content="http://apolo11teste.virtual.ufc.br/solar" />
  - <meta property="og:image" content="http://apolo11teste.virtual.ufc.br/solar/assets/logintopo.png" />
  - <meta property="og:site_name" content="SOLAR 2.0" />
  - <meta property="fb:app_id" content="259587414168382" />
